# Generated by Django 3.1.7 on 2021-03-19 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('mnit', models.CharField(max_length=1)),
                ('lname', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=9)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=15)),
                ('blood_type', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('weight', models.IntegerField(max_length=3)),
                ('height', models.IntegerField(max_length=2)),
                ('hmember', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_id', models.CharField(max_length=2)),
                ('available_from', models.DateField()),
                ('d_gender', models.CharField(max_length=1)),
                ('d_weight', models.IntegerField(max_length=3)),
                ('d_height', models.IntegerField(max_length=2)),
                ('d_age', models.IntegerField(max_length=2)),
                ('organizer_id', models.CharField(max_length=3)),
                ('storage_id', models.CharField(max_length=4)),
                ('ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.registeredusers')),
            ],
        ),
    ]
