# Generated by Django 3.1.7 on 2021-03-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredusers',
            name='hmember',
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='hmembership_no',
            field=models.IntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='ssn',
            field=models.IntegerField(max_length=9),
        ),
    ]
