# Generated by Django 3.1.7 on 2021-03-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210319_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredusers',
            old_name='height',
            new_name='height_in_lbs',
        ),
        migrations.RenameField(
            model_name='registeredusers',
            old_name='weight',
            new_name='weight_in_lbs',
        ),
    ]
